- name: install and run nginx 
  host: web
  become: yes 
  tasks:
    - name: install nginx
      ansible.builtin.pacakge:
      name: nginx
      state: present

    - name: start nginx
      ansible.builtin.server:
      name: nginx
      state: started 
      enable: yes 

